CREATE SEQUENCE IF NOT EXISTS files_email_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE if not exists answers
(
    id                VARCHAR(255)                NOT NULL,
    answer_text       VARCHAR(800)                NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    current_letter_id VARCHAR(255),
    user_by_id        VARCHAR(255),
    CONSTRAINT answers_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists files_email
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data      OID,
    name      VARCHAR(255),
    size      BIGINT,
    type      VARCHAR(255),
    letter_id VARCHAR(255),
    CONSTRAINT files_email_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists letter
(
    id            VARCHAR(255)                NOT NULL,
    active_letter BOOLEAN,
    watched       BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    delete_time   TIMESTAMP WITHOUT TIME ZONE,
    text          VARCHAR(5000)               NOT NULL,
    topic         VARCHAR(62)                 NOT NULL,
    by_user_id    VARCHAR(255),
    to_user_id    VARCHAR(255),
    CONSTRAINT letter_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists moved_letter
(
    id             VARCHAR(255) NOT NULL,
    type_of_letter VARCHAR(255) NOT NULL,
    will_delete_at TIMESTAMP WITHOUT TIME ZONE,
    letter_id      VARCHAR(255),
    moved_by_id    VARCHAR(255),
    CONSTRAINT moved_letter_pkey PRIMARY KEY (id)
);

CREATE TABLE if not exists users
(
    id        VARCHAR(255) NOT NULL,
    email     VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname  VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    username  VARCHAR(255) NOT NULL,
    roles     varchar(255)[],
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE files_email
    ADD CONSTRAINT fkb7v098hu9rjx607xy160y5xmj FOREIGN KEY (letter_id) REFERENCES letter (id) ON DELETE NO ACTION;

ALTER TABLE moved_letter
    ADD CONSTRAINT fkf75f6gx9bgecnsxat64ek0swc FOREIGN KEY (moved_by_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE letter
    ADD CONSTRAINT fkfc3g4pw9mc9s8hhvup47no5ti FOREIGN KEY (to_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE answers
    ADD CONSTRAINT fkgf1a4klhu60sw72xaqfiflk6t FOREIGN KEY (user_by_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE letter
    ADD CONSTRAINT fko4dvmsts1rc7c893fv4bg97fu FOREIGN KEY (by_user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE moved_letter
    ADD CONSTRAINT fkqwgv8r96c6qr079jpmamsybtd FOREIGN KEY (letter_id) REFERENCES letter (id) ON DELETE NO ACTION;

ALTER TABLE answers
    ADD CONSTRAINT fkx0fp8tw27xnqtsmv87jcwshy FOREIGN KEY (current_letter_id) REFERENCES letter (id) ON DELETE NO ACTION;